### ISSUE TITLE
Unsupported package manager on Alma Linux

### ISSUE THREAD

**Issue by CreepCoder** [oVirt/otopi#21]
Hello all,

I noticed that the installer will fail on an Alma Linux 8.5/8.6 machine. It will fail on the stage "Environment setup" with the following message:

No supported package manager found on your system

After that the setup stops. When trying on Rocky Linux, it will install without a problem. The distros should almost be the same, as they follow the EL8 standard. What could be the problem here? We use Alma Linux as our default OS, so it would be nice if we can get this to work.

Thank you in advance!

**Comment by didib** [comment]
Hi,

This isn't a support forum. Please email the oVirt users mailing list, and supply more details - versions of installed packages, relevant log files, etc. Thanks.

Support for AlmaLinux *should* have been added in https://github.com/oVirt/otopi/commit/2046d17d . 
See also https://bugzilla.redhat.com/2060006 . As noted there, I didn't try this myself.

**Comment by CreepCoder** [comment]
Thank you for your response! I will use the mailing list next time.
