### ISSUE TITLE
dnf plugin used private methods

### ISSUE THREAD

**Issue by mwperina** [oVirt/otopi#40]
Description of problem:

dnf-2 hidden some calls that used to be public, by prepending '_' to them.
otopi uses some of these, and currently works around this change by calling the hidden names. See also [bug 1455452](https://bugzilla.redhat.com/show_bug.cgi?id=1455452).

Using such private methods is a risk - dnf is allowed to drop them anytime, or change their signature or functionality, thus break otopi, and with it, all the tools that use it - including engine-setup, ovirt-host-deploy, etc.

So dnf should expose the functionality of these methods using official ones (see [bug 1542482](https://bugzilla.redhat.com/show_bug.cgi?id=1542482) for that) and then otopi should use these new official ones.

[1] https://bugzilla.redhat.com/showdependencytree.cgi?id=1455452&hide_resolved=0

Created from https://bugzilla.redhat.com/show_bug.cgi?id=1542492

**Comment by sandrobonazzola** [comment]
Fixed by #35
